const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
(async()=>{
 let body,requests=0,recorded=0;
 const context=vm.createContext({AbortController,setTimeout,clearTimeout,console,SIError:{describe:e=>e.message},LLMUsage:{record(){recorded++;}}});
 vm.runInContext(fs.readFileSync('plugin_src/chrome/content/scripts/llm_client.js','utf8'),context);
 context.fetch=async(_url,options)=>{requests++;body=JSON.parse(options.body);return {ok:true,headers:{get:()=> 'application/json'},json:async()=>({choices:[{message:{content:'answer'},finish_reason:'stop'}],usage:{total_tokens:20}})};};
 const config={llmApiBase:'https://api.deepseek.com/v1',llmApiKey:'test',llmModel:'deepseek-flash',llmProvider:'deepseek'};
 await context.LLMClient.complete([],config);
 assert.equal(body.thinking.type,'disabled');assert.equal(body.max_tokens,8192);
 await context.LLMClient.complete([],{...config,llmApiBase:'https://another.invalid/v1'});
 assert.equal(body.thinking,undefined);assert.equal(body.max_tokens,undefined);
 context.fetch=async()=>({ok:true,headers:{get:()=> 'application/json'},json:async()=>({choices:[{message:{content:'partial'},finish_reason:'length'}],usage:{total_tokens:4096}})});
 await assert.rejects(()=>context.LLMClient.complete([],config),/结果不完整/);assert.equal(recorded,3);
 let incomplete=false;
 const partial=await context.LLMClient.complete([],config,{allowPartial:true,onIncomplete:()=>incomplete=true});
 assert.equal(incomplete,true);assert.match(partial,/未完成/);assert.match(partial,/partial/);assert.equal(recorded,4);
 let partialRequests=0;
 context.fetch=async()=>{partialRequests++;return {ok:true,headers:{get:()=> 'application/json'},json:async()=>({choices:[{message:{content:'preserved evidence'},finish_reason:'length'}]})};};
 const paper=await context.LLMClient.analyzePaper('x'.repeat(90001),'paper_summary',config);
 assert.match(paper,/未完成/);assert.match(paper,/preserved evidence/);assert.equal(partialRequests,1,'partial analysis must stop subsequent requests');
 context.fetch=async(_url,options)=>{body=JSON.parse(options.body);return {ok:true,headers:{get:()=> 'application/json'},json:async()=>({choices:[{message:{content:'ok'},finish_reason:'stop'}]})};};
 await context.LLMClient.complete([],{...config,llmThinking:true,llmMaxTokens:16384});
 assert.equal(body.thinking.type,'enabled');assert.equal(body.max_tokens,16384);
 await assert.rejects(()=>context.LLMClient.complete([],{...config,llmMaxTokens:0}),/输出上限/);
 let aborted=false;requests=0;
 context.fetch=async(_url,options)=>{requests++;return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>{aborted=true;reject(Error('abort'));}));};
 await assert.rejects(()=>context.LLMClient.complete([],config,{timeoutMs:20}),/未自动重试/);
 assert.equal(aborted,true);assert.equal(requests,1);
 const controller=new AbortController();const pending=context.LLMClient.complete([],config,{signal:controller.signal,timeoutMs:1000});controller.abort();await assert.rejects(pending,/abort/);
 console.log('LLM controls passed: DeepSeek non-thinking/cap, other providers unchanged, truncation accounting, timeout without retry and external cancellation');
})().catch(error=>{console.error(error);process.exitCode=1;});
